### ISSUE TITLE
`mconcat . map` and formatting nitpicking

### ISSUE THREAD

**Issue by effectfully** [lpaste/lambda-paste#1]
There are a couple of uses of `mconcat . map` here:

```haskell
tokensToHtml :: [[(TokenType, String)]] -> H.Html
tokensToHtml =
  mconcat .
  map
    (\(i, line) ->
       H.tr H.! A.id ("line" <> fromString (show i)) $ do
         H.td
           (H.a H.! A.href ("#line" <> fromString (show i)) $ toHtml (show i))
         H.td
           (mconcat
              (map
                 (\(ty, str) ->
                    H.span H.! A.class_ (fromString (show ty)) $ toHtml str)
                 line))) .
zip [1 :: Int ..]
```

Why not `foldMap`?

It's a bit hard to read stuff like

```haskell
  mconcat .
  map
     (blah
       blah
         (blah
           blah
             (blah
               blah))) .
  zip [1 :: Int ..]
```

That last dot is not immediately visible, so my first though was "erm, what's going on here?".

Is this full source code of the new version of lpaste.net?

Thanks again for creating and maintaining lpaste.net, it is lovely.

**Comment by chrisdone** [comment]
Fair enough, I switched to `foldMap`. 👍 

> Is this full source code of the new version of lpaste.net?

Yep!
